spring:
  server:
    port: 8080
    security:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_demo?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: admin
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      logging:
        level:
          org.springframework.web: DEBUG
          org.thymeleaf: DEBUG